# -*- coding: utf-8 -*-
"""Mini-Project : Marketing Strategy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lo9Ehh4AJPx5xJK1--hxsYoL8IYqhUVh
"""

# from google.colab import files
import pandas as pd

# files.upload()

df = pd.read_excel("US Superstore data.xls", parse_dates=["Order Date", "Ship Date"])
df.info()
df.describe()

df.head()

print(df.isnull().sum())

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

state_sales = df.groupby("State")["Sales"].sum().sort_values(ascending=False)
plt.figure(figsize=(12,6))
sns.barplot(x=state_sales.index, y=state_sales.values, hue=state_sales.index, palette="viridis", legend=False)
plt.xticks(rotation=90)
plt.title("Ventes par État")
plt.show()
# L'état avec le plus de vente est la Californie

diff_ny_ca = df[df["State"].isin(["New York", "California"])].groupby("State")[["Sales", "Profit"]].sum()
diff_ny_ca.plot(kind="bar", figsize=(8,6), color=["blue", "green"])
plt.title("Comparaison des ventes et profits entre New York et Californie")
plt.ylabel("$")
plt.show()
# La Californie fait beaucoup plus de vente que New York mais il y a très peu de différence au niveau des profits

ny_outstanding_customers = df[df["State"] == "New York"].groupby("Customer Name")["Sales"].sum()
print("Meilleur client de New York :", ny_outstanding_customers.idxmax(), "avec", round(ny_outstanding_customers.max(), 3), "$ de ventes")

state_profitability = df.groupby("State")["Profit"].sum().sort_values()
plt.figure(figsize=(12,6))
sns.barplot(x=state_profitability.index, y=state_profitability.values, hue=state_profitability.index, palette="coolwarm_r", legend=False)
plt.xticks(rotation=90)
plt.title("Profit par État")
plt.show()

customer_profit = df.groupby("Customer ID")["Profit"].sum().sort_values(ascending=False)
cus_profit = customer_profit.cumsum() / customer_profit.sum()
top_20_percent_customers = int(len(customer_profit) * 0.2)
pareto_80_profit = cus_profit.iloc[top_20_percent_customers]

if pareto_80_profit >= 0.8:
  print(f"Les 20% des meilleurs clients génèrent {pareto_80_profit:.2%} du profit total")
else:
  print(f"Les 20% des meillerus clients génèrent {pareto_80_profit:.2%} du profit total donc moins de 80% donc on ne peut pas appliquer le principe de Pareto aux customers et profit")

city_sales = df.groupby("City")["Sales"].sum().sort_values(ascending=False).head(20)
city_profit = df.groupby("City")["Profit"].sum().sort_values(ascending=False).head(20)
fig, axes = plt.subplots(1, 2, figsize=(12,6))
sns.barplot(x=city_sales.index, y=city_sales.values, hue=city_sales.index, ax=axes[0], palette="Blues", legend=False)
sns.barplot(x=city_profit.index, y=city_profit.values, hue=city_profit.index, ax=axes[1], palette="Greens", legend=False)

axes[0].set_title("Top 20 villes par Ventes")
axes[0].tick_params(axis='x', rotation=90)
axes[1].set_title("Top 20 villes par Profit")
axes[1].tick_params(axis='x', rotation=90)
plt.tight_layout()
plt.show()


# Il y a des différence entre les villes qui font le plus de vente et les villes qui font le plus de profit
# Il y a des villes qui font moins de vente mais ont plus de profit

customer_sales = df.groupby("Customer Name")["Sales"].sum().sort_values(ascending=False).head(20)
plt.figure(figsize=(12,6))
sns.barplot(x=customer_sales.index, y=customer_sales.values, hue=customer_sales.index, palette="Oranges", legend=False)
plt.xticks(rotation=90)
plt.title("Top 20 clients par Ventes")
plt.show()

customer_sales_sorted = df.groupby("Customer ID")["Sales"].sum().sort_values(ascending=False)
cus_sales = customer_sales_sorted.cumsum() / customer_sales_sorted.sum()
plt.figure(figsize=(12,6))
plt.plot(cus_sales.values, label="Cumulative Sales")
plt.axvline(x=top_20_percent_customers, color='r', linestyle='dashed', label='20% Clients')
plt.axhline(y=0.8, color='g', linestyle='dashed', label='80% Sales')
plt.legend()
plt.title("Courbe cumulative des ventes par client")
plt.show()

# Prioriser le marketing sur les états de New York et Californie car on cherche les états et villes les plus rentables, mais aussi les meilleurs clients (The Pareto Principle)